id: I0B9032FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:28:35+00:00'
last_modified: '2022-06-07T16:15:36.606958+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16613
  title: ཇོ་བོའི་ཆོས་འབྱུང་བརྒྱ་རྩ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2DCC:
      image_group_id: I1KG16661
      title: ''
      total_pages: 570
      order: 1
      base_file: 2DCC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
